### ISSUE TITLE
Syntax error of awk

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-Automation#1]
https://github.com/CohenBerkeleyLab/BEHR-Automation/blob/e90843255b3765a53494f87ead49228103978c6f/get_modis.sh#L82
This should be:
```
fname=$(grep '.hdf' .listing | awk '{print $9}')
```

**Comment by behr-github** [comment]
From f33444221410de756e6a7d638a816f75ed83bf13 on, `get_modis.sh` is deprecated since the NASA data repository no longer accepts FTP connections. `get_modis.sh` was removed in 062cced93304e866eb6d4f056c100d3e9b55a8a3.
