### ISSUE TITLE
Update collection number of MYD06_L2

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-Automation#2]
https://github.com/CohenBerkeleyLab/BEHR-Automation/blob/b31a6ff4dc795ebdd587faef94ec4aa57ac8ae0a/MODIS_SOAP/get_modis_driver.py#L167

You can check the latest product number [here](https://modwebsrv.modaps.eosdis.nasa.gov/axis2/services/MODAPSservices/listProducts). The collection number of MYD06_L2 has been changed to 61.

**Comment by behr-github** [comment]
Updated in 062cced93304e866eb6d4f056c100d3e9b55a8a3
