### ISSUE TITLE
'write_urls' function lacks one parameter

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-Automation#3]
https://github.com/CohenBerkeleyLab/BEHR-Automation/blob/b31a6ff4dc795ebdd587faef94ec4aa57ac8ae0a/MODIS_SOAP/automodis.py#L114
'write_urls' function needs output_file name:
https://github.com/CohenBerkeleyLab/BEHR-Automation/blob/b31a6ff4dc795ebdd587faef94ec4aa57ac8ae0a/MODIS_SOAP/automodis.py#L49

**Comment by behr-github** [comment]
Fixed in 062cced93304e866eb6d4f056c100d3e9b55a8a3
